# Configuration Options
title: NeoObscura
author: "Kavi Dey, Henry Merrilees, Neil Chulani"
theme: minima

header-pages:
  - documentation.html
  - resources.html

baseurl: /NeoObscura

# Github Pages settings that cannot be changed
# lsi: false
# safe: true
# source: [your repo's top level directory]
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge
