# Configuration Options
title: NeoObscura
author: "Kavi Dey, Henry Merrilees, Neil Chulani"
theme: minima

header-pages:
  - documentation.html
  - resources.html

baseurl: /NeoObscura

plugins:
  - jekyll-katex

katex:
  js_path: "{{ Gem::lib_path }}/assets/js"  # Path used to search for katex.min.js
  rendering_options:
    # Default KaTeX rendering options. See https://github.com/Khan/KaTeX#rendering-options
    throw_error: true                       # throwOnError - set to false if you want rendering to output error as text rather than a build error
    error_color: "#cc0000"                  # errorColor

# Github Pages settings that cannot be changed
# lsi: false
# safe: true
# source: [your repo's top level directory]
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge
